### ISSUE TITLE
When BTC1 splits will they consider themselves bitcoin?

### ISSUE THREAD

**Issue by snavsenv** [btc1/bitcoin#102]
Hey, first of all i would like to apologise if i have come across as trollish on this github. But please bear with me. I was wondering if BTC1 will consider themselves Bitcoin after they hardfork? It could get ugly if they do, and i dont think its in the best interests of bitcoin or any of its participants.

**Comment by jgarzik** [comment]
This is off-topic and out of charter for NYA agreement.

**Comment by snavsenv** [comment]
What is that supposed to mean?
