### ISSUE TITLE
NYA/S2X Agreement & Deploying Full Nodes

### ISSUE THREAD

**Issue by BTCgithub** [btc1/bitcoin#108]
One component that seems to be missing from the S2X project is having NYA Signatories commit to rolling out more btc1/s2x Full Nodes. BS/Core has already indicated they intend to block/make the 2MB Fork more difficult by disconnecting S2X Nodes from the network.

BS/Core nodes have been continually used by the Core devs to attempt to hijack the Bitcoin network and force small block congestion/high fees so they can personally profit from future sidechain projects to relieve that network congestion. This node manipulation began with the dangerous UASF soft fork and they've indicated it will continue as the 2MB hard fork approaches.

The costs of deploying nodes is minor compared to the amount of time and money invested by Exchanges/Industry into infrastructure as well as the time and money spent securing the Bitcoin Network by Miners.

Shouldn't there be more NYA coordination/planning to deploy btc1/s2x Full Nodes prior to the 2MB Hard Fork? I post this here as the SegWit2x Team has established communication with the NYA Signatories, Industry members and miners that overwhelmingly support SegWit2x.

How many btc1/s2x nodes would be sufficient?

Some would argue centralization vs. decentralization.

Long gone are the days when home users would run full nodes as wallets due to the increase in current blockchain size, bandwidth costs and technical know-how required for the average bitcoin user. The Silent Majority of 1-2 million users are primarily using exchange/web wallet & SPV clients and they will never run Full Nodes. We should expect this trend to continue.

Previously decentralized user Full Nodes have evolved into being centralized/manipulated by said small group of developers. 

The existing 6000 Core nodes do not represent the Silent Majority of millions of Bitcoin Users. Core devs often run multiple node instances (Raspberry Pi, etc) so the actual number of unique individuals running Core nodes are fewer than 6000 people, probably much less than 1000.

Industry & Miners helping to deploy Full Nodes in large scale would be less developer centralized than the current state of the network. This blind spot regarding Full Nodes is being manipulated again and again even though 90%+ of the community is behind SegWit2x and scaling.

**Comment by betawaffle** [comment]
What is a DASF?

**Comment by buuser** [comment]
Currently there is only a release candidate available for btc1/NYA. 

Putting out an official release might help get more people to install it and spread the word that it is ready to go.

**Comment by betawaffle** [comment]
I'm not a core developer, I still run a full node.

**Comment by buuser** [comment]
> I'm hoping we can see more Industry/Miner involvement in deploying/decentralizing Full Nodes going forward in the project. The time when average users would deploy and run Full Nodes has passed us by due to cost/time/technical know how and Full Nodes no longer are representative of the millions of Silent Bitcoin users.

I think many users do still run full nodes, but even so, I was thinking that perhaps some companies/organizations might not be comfortable running software which does not have an official release ready. If we want people to run the software, we should be comfortable with releasing an official version.

**Comment by BTCgithub** [comment]
> I'm not a core developer, I still run a full node.

That's helpful for the community, but there are probably less than 1000 or so individuals doing so which has become disproportionate the to the number of silent bitcoin users. We need a more organized approach going forward since so few unique Bitcoin Users are deploying Full Nodes. There comes a mass adoption point where less technical users are involved, which is a good thing for Bitcoin growth but is causing node centralization (organizationally).

The NYA signatory industry/miners should really become involved with deploying Full Nodes to represent/support the millions of Users they serve/represent.

> buuser

We definitely need an official release so we can have more Full Nodes running before the 2MB Hard Fork and/or BS/Core starts rejecting btc1/s2x connections.

**Comment by JaredR26** [comment]
> The UASF was a misnomer and never supported by the Silent Majority of millions of Bitcoin "U=users", but rather a scheme pushed by the Core Developers, hence a 'D=Developer' activated soft fork.

Please don't make the arguments over terminology worse.  The developer part of this isn't strictly speaking true, and it only encourages more arguments over names and the meanings of things.  UASF has a name selected by its creators, and everyone knows what UASF means, even if they argue vehemently about the impact or support of the project.

The purpose of word choice is to communicate a concept.  We have enough contentious issues in this debate without adding even more bickering over terminology and semantics.

**Comment by BTCgithub** [comment]
> UASF

Edited out so as not to distract from the issue.

**Comment by mpatc** [comment]
The sooner miners/industry leaders publicly state they'll be moving along from core, the less turmoil, loss of value that will occur for everyone. Right now, the writing's on the wall, but unless you're following closely and reading obscure github threads, you'd have no idea it that the leadership/control over the dev process is about to drastically change. Most people have no idea, and that has the potential to cause a panic once it is widely known.

So the sooner the better.

Edit: if there's anything I can do to help get an official release out, please let me know.

**Comment by CosmicHemorroid** [comment]
@mpatc pay attention! https://www.coindesk.com/full-steam-ahead-segwit2x-reconfirm-bitcoin-hard-fork-plan/

**Comment by BTCgithub** [comment]
Further Reference: 

https://news.bitcoin.com/fork-wars-segwit-lock-in-and-communication-breakdown/
https://news.bitcoin.com/segwit2x-working-group-announces-the-hard-fork-roadmap/
http://www.trustnodes.com/2017/08/08/bitcoin-core-locks-segwit2x-clients
https://cointelegraph.com/news/bitcoin-core-developers-remain-adamant-in-opposition-to-segwit2x-potential-showdown-in-november

Core: Disconnect network service bits 6 and 8 until Aug 1, 2018   (or bits 5 and 7?)
https://github.com/bitcoin/bitcoin/pull/10982

**Comment by eumartinez20** [comment]
Users need to download the code and run it for SW2x to gain traction.

Multiple node creation by a few companies will likely not help much.

You have a valid point, but the seed change was a huge turn off for many, and without replay protection exchanges and companies involved in Bitcoin will not likely adopt it. I think more nodes can´t help how this is perceived.

**Comment by Bonez0r** [comment]
I'm just an ordinary user but i have run a Core node until recently. I'm very willing to run a full BTC1 node. I'm not enough of a techie to build the client myself though, so an executable or a zip with pre-built release would be great. There are probably hundreds to thousands more like me. Even if people like me run the nodes only temporarily, it would still be a big help in the transition where BTC1 needs all the traction and confidence it can get. Once past critical mass, the rest of the Core network will switch to BTC1.

Even in this early stage, a higher number of nodes would signal that there is plenty of support. This would give onlookers more confidence to make the switch as well.

So can we expect an official pre-built release in the near future? The sooner the better, especially with Core's recent plan to block S2x nodes.

**Comment by jgarzik** [comment]
Agree w/ sentiment - we created some pre-built binaries and have some other related ideas ready for release today/tomorrow...   Great ideas and suggestions, all!
