### ISSUE TITLE
Review impact and ratify or reject the hard fork

### ISSUE THREAD

**Issue by rodasmith** [btc1/bitcoin#115]
# Problem

The New York Agreement included the ambiguous goal of "2 MB" blocks, but there are multiple potential interpretations of that due to the technical nature of block weights with SegWit. The Btc1 team interpreted that goal as inflating the full block size to 8 MW, which would produce blocks of about 4 MB including witness data. It is not clear whether all the signatories had the same understanding of which part of the block would have the 2 MB size nor whether they fully understood the economic impact of such a change.

## Mitigation option

To help ensure that everyone makes an informed decision on such an important matter, we plan to analyze of the costs and benefits of a hard fork to 4 MB blocks https://github.com/NYAcoin/bitcoin/issues/5 and we invite the other teams to do the same. Whatever the findings, we invite the signatories to review them and to deliberate carefully on whether to ratify or reject the hard fork.

**Comment by mpatc** [comment]
NAK NYA was clear, claiming people didn't understand that 8MB means 8MB is a fake red herring. Please stop being patronising. 

I think @rodasmith needs a time out, there is a clear line between contribution and trolling, and the comments from this person show someone who determined to undermine the NYA and this project.
