### ISSUE TITLE
Measure success

### ISSUE THREAD

**Issue by rodasmith** [btc1/bitcoin#116]
# Problem

There is no easy way for the signatories of the New York Agreement to evaluate whether the terms of the Agreement have been reached.

# Solution proposal

A report or dashboard should be built to measure progress against the goals of the Agreement:

* Activate Segregated Witness at an 80% threshold, signaling at bit 4
* Activate a 2 MB hard fork within six months

Such a report could show whether Segregated Witness is activated (e.g. something like https://xbt.eu/ ) and a separate indicator could show the size of blocks.

**Comment by christophebiocca** [comment]
Given the behaviour of the code as currently deployed, both of these can be reliably tracked by the block-height indicator.

481824 => SegWit activates.
494784 => A block > 1MB is created and the hard fork occurs.

Not sure what's left to track?

**Comment by rodasmith** [comment]
Do you have a link to a particular report that the signatories could review so they can easily see whether the 2 MB block size has been achieved?

**Comment by christophebiocca** [comment]
Generating a report or a webpage wouldn't be in the spirit of Bitcoin, as it'd require unnecessary trust. However many services do track the current height of the chain, such as blockchain.info, should you be willing to trust them.

For anyone running a btc1 node, the following shell script can tell you whether segwit is activated or not, and whether the 2MB branch is activated or not:

```
((`bitcoin-cli getblockcount` >= 481824)) && echo "Segwit activated" || echo "Segwit not activated"
((`bitcoin-cli getblockcount` >= 494784)) && echo "2MB activated" || echo "2MB not activated"
```

You can even loop it using `watch` so it updates in near-real-time.

**Comment by rodasmith** [comment]
That is not helpful for people who cannot read the Btc1 code. Signatories and the public need a way to see the block size on a testnet chain and on the main chain so they can be convinced of success without reading code.

**Comment by rodasmith** [comment]
That is not helpful for people who cannot read the Btc1 code. Signatories and the public need a way to see the block size on a testnet chain and on the main chain so they can assess success without reading code.

**Comment by mpatc** [comment]
What's the word for "trying something that has failed and expecting a
different result"?

**Comment by jheathco** [comment]
"rodasmith"?  @christophebiocca he's obviously trolling.

**Comment by tobakk** [comment]
best solution- -> #NO2X

**Comment by hoffmabc** [comment]
Can we just close this issue? @rodasmith is clearly continuing the same useless attempt to say that segwit as it stands meets the NYA agreement. I think this has already been addressed so this issue is another unnecessary waste of time.

cc:@jgarzik
