### ISSUE TITLE
Docker/Kubernetes configurations for launching BTC1 nodes.

### ISSUE THREAD

**Issue by zquestz** [btc1/bitcoin#128]
I am posting here based on my conversation with @jgarzik today. Right now getting more 2X nodes in the wild is super important, so I think links or docs pointing to Docker Images and Kubernetes configurations could be very useful for the project.

Here is a docker image for 1.14.5 which is available at: https://github.com/zquestz/docker-bitcoin/tree/master/btc1/1.14.5

You can also download it from Docker Hub at https://hub.docker.com/r/zquestz/bitcoin-btc1/

It seems 1.15.0 is being released soon, as I see an unfilled entry for it on the releases page. I will update the images to 1.15.0 when it is available.

In addition I have Kubernetes configurations for GCE that might be useful. They are available via the following gist: https://gist.github.com/zquestz/0007d1ede543478d44556280fdf238c9

Let me know if you need anything else. =)

**Comment by anton000** [comment]
A sample conf file would be helpful as well

**Comment by zquestz** [comment]
The conf is available in the github repo. https://github.com/zquestz/docker-bitcoin/tree/master/btc1/1.14.5

Just look at the Dockerfile. =)

**Comment by bitPico** [comment]
There is already ~900 SegWit2x compatible nodes; you'd sacrifice network decentralization by leading people to the same VPS providers as a single point of failure. It's cheaper to run a few nodes on existing hardware using different VPN's. This way you are not in a single point of failure scenario; your nodes can be placed anywhere in the world; most homes or businesses have 10-100 Megabit connections if not Gigabit fiber with close to FIVE-NINES (https://en.wikipedia.org/wiki/Five_nines).

**Comment by zquestz** [comment]
Umm, that's why I provided the Docker image, that can be run anywhere. The kubernetes configurations were only provided as a bonus, as I wrote them for myself 3 months ago.

Why is everyone so negative? Seems no one ever has anything nice to say.

**Comment by JaredR26** [comment]
> Why is everyone so negative? Seems no one ever has something nice to say.

Everyone is on edge. :(  Everything is a perceived attack.

Your image was extremely helpful for me.  Thank you.

**Comment by AllanDoensen** [comment]
@zquestz Nice work, thanks :-)

**Comment by rfree-d** [comment]
> Right now getting more 2X nodes in the wild is super important

Isn't it a lack for support for project if nodes can't grow organically by actual real users choosing to switch to btc1 code?

![](https://kek.gg/i/6wVdQ5.jpeg)
