### ISSUE TITLE
Long-term game-theoretic perspective

### ISSUE THREAD

**Issue by fortran77** [btc1/bitcoin#132]
I am sorry, the following doesn't fit the provided issue template. I'll make it brief.

From a long-term game-theoretic perspective:

The btc1 developers should do everything possible to ensure that everybody running a full node will find it convenient to use the btc1 distribution **even if they don't they want segwit2x active**.

**Comment by omersiar** [comment]
"should do everything possible" it sounds like Core.

**Comment by bitPico** [comment]
Our full node code was written from the ground up (non-Satoshi) and we are SegWit2x ready besides using a single codebase to run a multibillion dollar computer network is plain ignorance.

NACK

**Comment by fortran77** [comment]
You all are playing a short-term game. You might even win in November. Core is in it for the long haul. They are placing their pawns and aligning their bishops, so to speak, and preparing for a long and hard end game. If the comments that I see above reflect your long-term strategy, then you might win a battle or two, and then you will lose the war.

**Comment by chiwalfrm** [comment]
NACK.  Please keep issues technical.  Github isn't a tool for political or game-theory.

**Comment by jgarzik** [comment]
I think people are reacting to the issue title, whereas I am mentally "clicking for detail"

I'm going to close this issue, because as @chiwalfrm and others note, github is for technical issues.

It _is_ quite valid to file an issue that moves towards @fortran77 's goal.  For example, an issue "create Ubuntu PPA repository for btc1" would be a reasonable github issue to file.

**Comment by fortran77** [comment]
There's always hope, but [for now](https://lists.linuxfoundation.org/pipermail/bitcoin-segwit2x/2017-November/000685.html) the score is:

game theory:1, technical merit:0
