### ISSUE TITLE
Windows Build error making depends

### ISSUE THREAD

**Issue by fmarcosh** [btc1/bitcoin#137]
### Describe the issue
I'm trying to install a btc1 node in a Windows 10 machine following the Windows build instructions. In the depends making step I get the following
paco@pacoi5-PC:/mnt/j/Descargas/bitcoin-segwit2x/depends$ make HOST=x86_64-w64-mingw32
Fetching ccache-3.3.3.tar.bz2 from https://samba.org/ftp/ccache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   261  100   261    0     0    153      0  0:00:01  0:00:01 --:--:--   153
100  337k  100  337k    0     0   127k      0  0:00:02  0:00:02 --:--:--  949k
/mnt/j/Descargas/bitcoin-segwit2x/depends/work/download/native_ccache-3.3.3/ccache-3.3.3.tar.bz2.temp: La suma coincide
Extracting native_ccache...
/mnt/j/Descargas/bitcoin-segwit2x/depends/sources/ccache-3.3.3.tar.bz2: La suma coincide
Preprocessing native_ccache...
Configuring native_ccache...
/bin/sh: 1: Syntax error: "(" unexpected
funcs.mk:242: fallo en las instrucciones para el objetivo '/mnt/j/Descargas/bitcoin-segwit2x/depends/work/build/x86_64-w64-mingw32/native_ccache/3.3.3-3a8c082237f/./.stamp_configured'
make: *** [/mnt/j/Descargas/bitcoin-segwit2x/depends/work/build/x86_64-w64-mingw32/native_ccache/3.3.3-3a8c082237f/./.stamp_configured] Error 2
The following tries we get the same message
paco@pacoi5-PC:/mnt/j/Descargas/bitcoin-segwit2x/depends$ make HOST=x86_64-w64-mingw32
Configuring native_ccache...
/bin/sh: 1: Syntax error: "(" unexpected
funcs.mk:242: fallo en las instrucciones para el objetivo '/mnt/j/Descargas/bitcoin-segwit2x/depends/work/build/x86_64-w64-mingw32/native_ccache/3.3.3-3a8c082237f/./.stamp_configured'
make: *** [/mnt/j/Descargas/bitcoin-segwit2x/depends/work/build/x86_64-w64-mingw32/native_ccache/3.3.3-3a8c082237f/./.stamp_configured] Error 2
paco@pacoi5-PC:/mnt/j/Descargas/bitcoin-segwit2x/depends$
### Can you reliably reproduce the issue?
Yes

### Machine specs:
- OS: Windows 10
- CPU: Intel i5
- RAM: 4GB
- Disk size: 1TB
- Disk Type (HD/SDD): HDD

**Comment by donaloconnor** [comment]
This is regarding the importing of the Windows %PATH% var. Please follow the more up to date instructions on: https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md

**Comment by fmarcosh** [comment]
Thanks donaloconnor, this step fixed but further we get:

config.status: executing depfiles commands
config.status: executing libtool commands
Building native_protobuf...
make[1]: se entra en el directorio '/mnt/j/Descargas/bitcoin-segwit2x/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-f5a1828c825/src'
make[2]: se entra en el directorio '/mnt/j/Descargas/bitcoin-segwit2x/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-f5a1828c825'
 cd . && /bin/bash /mnt/j/Descargas/bitcoin-segwit2x/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-f5a1828c825/missing automake-1.14 --foreign
/mnt/j/Descargas/bitcoin-segwit2x/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-f5a1828c825/missing: línea 81: automake-1.14: orden no encontrada
WARNING: 'automake-1.14' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:612: fallo en las instrucciones para el objetivo 'Makefile.in'
make[2]: *** [Makefile.in] Error 1
make[2]: se sale del directorio '/mnt/j/Descargas/bitcoin-segwit2x/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-f5a1828c825'
Makefile:1222: fallo en las instrucciones para el objetivo 'Makefile.in'
make[1]: *** [Makefile.in] Error 1
make[1]: se sale del directorio '/mnt/j/Descargas/bitcoin-segwit2x/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-f5a1828c825/src'
funcs.mk:242: fallo en las instrucciones para el objetivo '/mnt/j/Descargas/bitcoin-segwit2x/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-f5a1828c825/./.stamp_built'
make: *** [/mnt/j/Descargas/bitcoin-segwit2x/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-f5a1828c825/./.stamp_built] Error 2

**Comment by fmarcosh** [comment]
It seems that the script files uses the automake-1.14 command and I have a newest version (automake-1.15)

**Comment by fmarcosh** [comment]
An extra action needed in my case.
In the bash session go to the directoy bitcoin-segwit2/depends/work/build/x86_64-w64-mingw32/native_protobuf/2.6.1-f5a1828c825
and run ./autogen.sh
if autogen is not installed run previously sudo apt-get install autogen.
