### ISSUE TITLE
testnet5 issues

### ISSUE THREAD

**Issue by jheathco** [btc1/bitcoin#22]
Compiled on OS X and running into syncing issues while downloading headers.  Each time it gets to 86.58% before stalling.  Anyone else experiencing this?

http://drop.johnheathco.com/pb-8vbD4I7HEW.png

**Comment by hoffmabc** [comment]
I didn't see that but I'll give it a shot again in the morning.

**Comment by joshafest** [comment]
had you tried again synchronisation after restart?

**Comment by jheathco** [comment]
It appears to be working today and completed the sync successfully.  Closing this off.

**Comment by philbertw4** [comment]
experiencing the same issue -- requesting that this be reopened

rc1 build, ubuntu...stalled at:
Number of blocks left   Unknown. Syncing Headers (16000)...
Last block time             Sat Jun 17 11:05:49 2017
Progress                       87.36%
