### ISSUE TITLE
Application stability concerns

### ISSUE THREAD

**Issue by MrHash** [btc1/bitcoin#26]
I am concerned about installing this software because it is not clear what testing and security mechanisms are in place to ensure that the releases are reliable. Could you elaborate on what measures you have in place as it would be in the interests of everyone because a massive amount of business depends on the reliability and security of these releases. I understand these are only release candidate/alpha versions but since they are relatively new the concerns arise. Many thanks

**Comment by jgarzik** [comment]
Great questions.

Some of the things that are in place:

* gitian builds by multiple developers (see gitian.sigs repo)
* open, public test network testnet5, with companies actively testing their software stacks on top of this
* internal activation (before/SW/SW2x) scenario testing
* external activation and scenario testing on testnet5 and private testnets
* auditing and testing of software stacks for block size sensitivity
* development of specifications (see specifications repo) - proposed BIPs - for review

Some people have also suggested migration guides and other documentation, further packaging and several other great suggestions which can be followed up on.

**Comment by MrHash** [comment]
Ok thanks for taking the time to make the response. One thing that concerns me is that it appears you are the lead developer on this fork, yet you apparently do not have any significant track record as a Bitcoin developer although it appears you have some experience with mining. How can the public and theirs billions of investment be sure that you know what you are doing? How do we establish trust, or is it a case of "fingers crossed"?

**Comment by NiKiZe** [comment]
@MrHash Some references that you might find interesting (and I would say contradicts your statement)

https://en.bitcoin.it/wiki/Jeff_Garzik
https://github.com/bitcoin/bitcoin/commits?author=jgarzik

**Comment by JaredR26** [comment]
> One thing that concerns me is that it appears you are the lead developer on this fork, yet you apparently do not have any significant track record as a Bitcoin developer although it appears you have some experience with mining.

I'm not sure where you got this, but it is not correct.  Jeff is one of the
most experienced developers in Bitcoins history with an extremely high
number of executed changes.  There probably a lot more history around why
you have been lead to believe otherwise than belongs here, but you can send
me an email if you're curious.

**Comment by MrHash** [comment]
@NiKiZe unfortunately these references precisely confirm my concerns... i guess the complete commit history is not available on Github. Perhaps somewhere else?

**Comment by jgarzik** [comment]
Github shows less than 1% of the history.

```
$ git log | grep Author | grep -ci wuille
1382
$ git log | grep Author | grep -ci gavin
1122
$ git log | grep Author | grep -ci garzik
533
$ git log | grep Author | grep -ci maxwell
252
```

**Comment by JaredR26** [comment]
Doing development since at least early 2011:
https://bitcointalk.org/index.php?topic=4254.msg61773#msg61773

August 2011, interview with description: "Jeff Garzik a Linux Kernel and Bitcoin developer speaks about the state of Bitcoin."
https://www.youtube.com/watch?v=fRjEd8NS4Wc

Author of BIPs 35 (August 2012) and 102 (June 2015)
https://github.com/bitcoin/bips/blob/master/README.mediawiki

This isn't hard to find, and it doesn't really have any relevance to the code or process, Jeff isn't acting alone here.  The information on how we got here is out there if you want to find it, otherwise Jeff has answered the technical questions here.

**Comment by MrHash** [comment]
Ok thanks for the info once again, i'll do some more research. However, I don't think it's off-topic since I have no other forum to participate in where I can do diligence or determine what the consequences are for the greater community. This is supposed to be open source software after all. The risk to Bitcoin is apparent and like many others I will have mitigate against a possible loss of investment. 

Do you have a support channel, gitter, slack or something?

**Comment by MrHash** [comment]
Also @JaredR26 your lack of any Github activity raises concerns also. No offence, but it's not clear who you are or what your association to Bitcoin is, yet you are assuming an air of responsibility.

**Comment by JaredR26** [comment]
> However, I don't think it's off-topic since I have no other forum to participate in where I can do diligence or determine what the consequences are for the greater community.

Questioning the committers' qualifications is going to be off topic in virtually any open source project, including the main Bitcoin repository.  The code is open source, the point is to discuss the code and it's implications, not the qualifications of people contributing(or even commenting).

> Also @JaredR26 you lack of any Github activity raises concerns also.

I'm not a committer, I'm weighing in with my thoughts relevant to the code changes and proposals.

> No offence, but it's not clear who you are or what your association to Bitcoin is, yet you are assuming a air of responsibility.

I'm not assuming anything.  I'm responding to what you're saying and suggesting courses of actions, the purpose of github discussions.  I could ask you who you are to question the qualifications of Jeff based on nothing, but I shouldn't care and don't, and it isn't relevant to the technical discussions.

**Comment by MrHash** [comment]
You are right this is not the appropriate place for raising non-technical concerns. However you should have setup a forum for community discussion, especially for a project of such importance as this with a massive amount of value attached to it.

As I understand it, one of the major reasons this fork exists is to decentralize Bitcoin governance and make it more transparent. At the moment you are NOT building confidence in that objective by shutting down a reasonable line of questioning, albeit in the wrong place.

I am one of perhaps millions of investors in Bitcoin who are concerned about its future and its impact on society in the short and long term. That is ample justification for asking about the credentials of the developers behind this project.

Where is your community discussion channel? Core & UASF have a busy community channel and I have asked many questions there too.

**Comment by opetruzel** [comment]
@MrHash
Are you aware of the SegWit2x mailing list? Information and registration is here:  
https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-segwit2x

That is likely a more appropriate medium for this type of discussion.

**Comment by MrHash** [comment]
@opetruzel thanks for the link. I have joined the mailing list and await moderation, but I have to say using an archaic medium such as that does not inspire much confidence. We can end this discussion here, and hopefully continue over there where I hope this issue of governance and transparency can be discussed. Thank you.

**Comment by opetruzel** [comment]
@MrHash 
A linuxfoundation mailing list is the EXACT SAME MEDIUM used by all Core developers for the last several years. Can I assume you've let Core know that their preferred medium for all/most dev-related discussions is "archaic," as well? I'm beginning to suspect that you're just concern trolling...

**Comment by MrHash** [comment]
Sorry I did not know that, but then that's not a community channel, that's a development channel. It is also archaic IMHO if they also still use that. I'm still left not knowing where I should take this discussion and if anyone cares about what I think.

**Comment by dexX7** [comment]
@NiKiZe @MrHash:

For some reason most commits are not properly shown, but here is a list with more than 150 (!) pull requests made by @jgarzik:

https://github.com/bitcoin/bitcoin/pulls?q=author%3Ajgarzik

**Comment by hoffmabc** [comment]
I think this thread could be summarized by "thanks for telling me that, but..."

**Comment by MrHash** [comment]
@hoffmabc thanks for your summary, but I gain nothing from reading it other than maybe I should vary my protocol. Let me think about that.

Actually the thread could be summarized as a failing attempt to establish trust with the team to safely fulfil a promise of decentralization of development without risking the stability and value of Bitcoin.

**Comment by hoffmabc** [comment]
Yes your intent was clear from the beginning @MrHash. If you don't even know Jeff's extensive previous history working with Bitcoin then I'd say you've most likely come here to concern troll based on input you got elsewhere. 

You started off with reasonable questions but when you got an answer you proceeded to walk everyone down a list of complaints and criticisms you had. This is not the forum for wanton concern trolling.

**Comment by MrHash** [comment]
@hoffmabc what utter nonsense. I seek proof that your people are safely decentralizing development and not recklessly leading Bitcoin to a centralized future. This is already looking like it will have a massive impact on Bitcoin's reputation. I don't need you coming in and complaining about my concerns, that's not how you build community in OSS.

As I have stated before, this is the only place i can participate in that discussion for lack of an open alternative. I have not yet been approved for the mailing list.

What is the agenda for this fork some months down the road? Will it continue and how will you decentralize development more than it has been so far? At the moment this is looking like a power grab.
