### ISSUE TITLE
Remove fixed activation date (BIP102_FORK_MIN_HEIGHT)

### ISSUE THREAD

**Issue by jgarzik** [btc1/bitcoin#27]
This code becomes moot on June 21; remove.   The remaining logic "SegWit + 3 months" becomes less complex with this change.

This existed for the case miners activated Bit-4 very aggressively and early, but is not needed anymore.

**Comment by Buck-Rogers** [comment]
There is no code associated with this issue. But I am assuming you are referring to the old HF in at a fixed point in mid September code. Yes it should go IMHO. 

What was the rationale behind +3 months? I would think that if 80%+ were running segwit2x or BU then 1 month would be enough.

**Comment by mpatc** [comment]
https://github.com/btc1/bitcoin/pull/36

**Comment by jgarzik** [comment]
Fixed by #48
