### ISSUE TITLE
Unexpected version warning

### ISSUE THREAD

**Issue by vogelito** [btc1/bitcoin#30]
### Describe the issue
Running the btc1/bitcoin codebase with the testnet flag (testnet5), my client starts warning:
`warning='100 of last 100 blocks have unexpected version'`. This warning should be removed to accommodate the new version.

Various `bicoin-cli` calls also display the following error: `"Warning: Unknown block versions being mined! It's possible unknown rules are in effect"`. (e.g. `getinfo`, `getnetworkinfo`)

### Can you reliably reproduce the issue?
Yes.

#### If so, please list the steps to reproduce below:
1. git clone btc1/bitcoin
2. git checkout 6b0ef27b85c2093dca40a264382c336eb5727316 on segwit2x branch
3. compile
4. run bitcoind with -testnet flag
5. You start getting warnings on `debug.log` on block `00000000036e8095f5248aeeea44b6925d292cec86e8d75e2240b343a1841f24` 
6. You should also see the warning when issuing the `getinfo` command via `bitcoin-cli`.

```
2017-06-20 00:56:35 UpdateTip: new best=00000000036e8095f5248aeeea44b6925d292cec86e8d75e2240b343a1841f24 height=16777 version=0x20000012 log2_work=49.050508 tx=27654 date='2017-06-19 01:09:17' progress=0.874407 cache=3.4MiB(16990tx) warning='27 of last 100 blocks have unexpected version'
```

### Expected behaviour
debug.log shouldn't throw those warning messages.

### Actual behaviour
debug.log has warning messages which might be confusing to users upgrading to segwit2x clients

### What version of bitcoin-core are you using?
Self-compiled 6b0ef27b85c2093dca40a264382c336eb5727316 on segwit2x branch in btc1/bitcoin

### Machine specs:
- OS: Ubuntu 16.04.2 LTS
- CPU: 2x Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
- RAM: 3.8GB
- Disk size: 512GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
```
# cat .bitcoin/bitcoin.conf 
txindex=1
mempoolexpiry=1344
testnet=1
```

```
# bitcoin-cli getnetworkinfo
{
  "version": 1140100,
  "subversion": "/Satoshi:1.14.1/",
  "protocolversion": 70015,
  "localservices": "000000000000000d",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 3,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    }, 
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    }, 
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001000,
  "incrementalfee": 0.00001000,
  "localaddresses": [
  ],
  "warnings": "Warning: Unknown block versions being mined! It's possible unknown rules are in effect"
}
```

```
# bitcoin-cli getinfo
{
  "version": 1140100,
  "protocolversion": 70015,
  "walletversion": 130000,
  "balance": 0.00000000,
  "blocks": 18844,
  "timeoffset": 0,
  "connections": 3,
  "proxy": "",
  "difficulty": 256,
  "testnet": true,
  "keypoololdest": 1497920141,
  "keypoolsize": 100,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": "Warning: Unknown block versions being mined! It's possible unknown rules are in effect"
}
```

**Comment by vogelito** [comment]
The first occurrence in my logs:
```
2017-06-20 00:56:35 UpdateTip: new best=00000000036e8095f5248aeeea44b6925d292cec86e8d75e2240b343a1841f24 height=16777 version=0x20000012 log2_work=49.050508 tx=27654 date='2017-06-19 01:09:17' progress=0.874407 cache=3.4MiB(16990tx) warning='27 of last 100 blocks have unexpected version'
```

The last message in my logs with that warning is:
```
2017-06-24 22:42:12 UpdateTip: new best=00000000000ec96edc8fac1164cdb3d6585126f080afab239b45a27a31a6f6dd height=22997 version=0x20000000 log2_work=54.547191 tx=47953 date='2017-06-24 22:
42:09' progress=1.000000 cache=0.3MiB(262tx) warning='1 of last 100 blocks have unexpected version'
```


I just updated to btc1 Core version 1.14.3 and now I see new warnings:
```json
$ ./bitcoin-cli getnetworkinfo
{
  "version": 1140300,
  "subversion": "/Satoshi:1.14.3/",
  "protocolversion": 70015,
  "localservices": "000000000000000d",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 8,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    }, 
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    }, 
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001000,
  "incrementalfee": 0.00001000,
  "localaddresses": [
  ],
  "warnings": "Warning: unknown new rules activated (versionbit 4)"
}
```

```json
./bitcoin-cli getinfo
{
  "version": 1140300,
  "protocolversion": 70015,
  "walletversion": 130000,
  "balance": 0.00000000,
  "blocks": 24847,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 7750.571624499224,
  "testnet": true,
  "keypoololdest": 1497920141,
  "keypoolsize": 100,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": "Warning: unknown new rules activated (versionbit 4)"
}
```

**Comment by tomasvdw** [comment]
I have reproduced and found the cause.

This seems to be the result of miners on testnet5 mining with a custom "-blockversion". The given blocks are _after_ activation of SegWit2X but are still signaling due to manual override. Without manual override this wouldn't happen as the ComputeBlockVersion() is working as expected.

It would be nice if testnet5 miners could confirm that they have been doing this, although I am quite certain that this is the cause.

This is the intended behavior as consequence of using manual blockversion override.

**Comment by vogelito** [comment]
I just built what was released in the [v1.14.4](https://github.com/btc1/bitcoin/releases/tag/v1.14.4) tag.

Still seeing the warning message in testnet5:
```json
$ bitcoin-cli getnetworkinfo
{
  "version": 1140400,
  "subversion": "/Satoshi:1.14.4(2x)/",
  "protocolversion": 70015,
  "localservices": "000000000000000d",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 8,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    }, 
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    }, 
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001000,
  "incrementalfee": 0.00001000,
  "localaddresses": [
  ],
  "warnings": "Warning: unknown new rules activated (versionbit 4)"
}
```

**Comment by christophebiocca** [comment]
Yeah, this is expected. Some people are still setting bit4 even post activation. By the design of BIP8, this is interpreted as a brand new (and thus unknown) proposal.

There's nothing to do about it expect tell them to stop hogging a now-inactive signalling bit, it's working as expected.

**Comment by jgarzik** [comment]
Agreed
