### ISSUE TITLE
Making fork params network-specific

### ISSUE THREAD

**Issue by chjj** [btc1/bitcoin#33]
Might be good to refactor a bit and move `BIP102_FORK_MIN_HEIGHT` and `BIP102_FORK_BUFFER` to chainparams. This would allow us to test the hardfork on testnet5 without mining up to height 485k.

**Comment by chjj** [comment]
Didn't see this: https://github.com/btc1/bitcoin/issues/27

Closing.

**Comment by jgarzik** [comment]
Agree that it you want to move this into chainparams to vary it per-chain
