### ISSUE TITLE
testnet5 faucet

### ISSUE THREAD

**Issue by jheathco** [btc1/bitcoin#37]
Is there a faucet for testnet5?

**Comment by jheathco** [comment]
I've built small chain explorer for testnet5 here (I'll get a more friendly URL later):

http://btcfaucet.ix28uktqsp.us-west-2.elasticbeanstalk.com/

The faucet code is just about ready, however I'll need to seed an address with some funds that I can distribute.  If any miner can send some coins please shoot them over to:

mjL4CJME52XPFmsCa3FKoCkp4NqrBGt5Ho

Hopefully this should get a bit more activity going on the testnet.

**Comment by jheathco** [comment]
This is up and running and you can request 0.5 BTC at a time.  Not sure if we want to throw this up somewhere to make people more aware of it?  Perhaps https://segwit2x.github.io/?

**Comment by jgarzik** [comment]
Thanks for the effort!

Best place to post this is the segwit2x.github.io repo/page, as @philbertw4 appears to have done via his PR.
