### ISSUE TITLE
Conflict of interest?

### ISSUE THREAD

**Issue by taoeffect** [btc1/bitcoin#39]
How can the owner of a [company that helps people trace bitcoin transactions](https://www.reddit.com/r/Bitcoin/comments/5wh3bk/jeff_garziks_company_bloq_buys_blockchain/) be trusted to work on this?

**Comment by mpatc** [comment]
How can we take someone who appropriates religious symbols seriously?

**Comment by taoeffect** [comment]
To make the conflict of interest clear: the lead (?) dev of this project is financially incentivized (makes profit) off of destroying whatever privacy the blockchain offers to people.

This is a clear conflict of interest.

**Comment by mpatc** [comment]
Again, why should anyone take you seriously? 

To risk feeding a reddit troll, if the Bitcoin blockchain loses its value, how does he profit.

And Mr. tao, do you have any interest in seeing Bitcoin fail? You wouldn't be involved with other cryptos, would you? It seems like you stand to gain from spreading FUD here, amirite?

**Comment by taoeffect** [comment]
This has nothing to do with me.

EDIT: this was in reply to user @mpatc, who appears to have deleted his comments. If you are curious and want some amusement [here's a screenshot of some of the comments he posted](https://fixingtao.com/other/images/funny-btc1-person.jpg) (read from bottom up).

**Comment by mpatc** [comment]
I see, you don't want to answer tough questions. Just here to spread some FUD? Why not go work on your cute little mystical tao tokens, or whatever?

**Comment by taoeffect** [comment]
> I see, you don't want to answer tough questions.

Your questions have nothing to do with the issue.

**Comment by mpatc** [comment]
> if the Bitcoin blockchain loses its privacy, it obviously crashes value, so how does he profit, exactly?

**Comment by taoeffect** [comment]
> if the Bitcoin blockchain loses its privacy, it obviously crashes value, so how does he profit, exactly?

Um, he's profiting the entire time, in U.S. dollars or whatever currency he's accepting for tracing bitcoin transactions.

The price of Bitcoin might fall or rise during this time, #btc1 will probably disappear like every other HF attempt of Bitcoin, but none of that changes the fact that there is a clear conflict of interest on his behalf.

**Comment by mpatc** [comment]
#dragonsden

**Comment by mpatc** [comment]
So why are you here? Don't you have TaoCrystalCoin to work on?
Edit: I deleted my comments because I realised I was feeding a troll, and that's always a bad idea.

I think there is enough space in the crypto world for bitcoin and TaoCrystalCoins, so I wish you the best TaoCrystalCoin troll. I look forward to giving some to my little cousin so she can play MapleStory, or whatever.

**Comment by whitematrix62** [comment]
@taoeffect it's open sourced. feel free to review the code and contribute.

**Comment by whitematrix62** [comment]
@taoeffect you cannot destroy privacy when bitcoin is inherently traceable in the 1st place.
