### ISSUE TITLE
Enable voluntary relaying and mining of Segregated Witness transactions

### ISSUE THREAD

**Issue by jmprcx** [btc1/bitcoin#43]
Miners and node operators who do not agree with Segregated Witness activation should be given a passive means to protest SegWit activation without breaking consensus or initiating a chainsplit.

The inclusion of a command line flag `-opt-out-segwit` enables node and mining pool operators to disallow inclusion of Segregated Witness transactions into blocks or for them to be relayed over the network.

**Comment by jameshilliard** [comment]
Unneeded, GBT won't include segwit transactions already if stratum server doesn't support it.

**Comment by JaredR26** [comment]
Agree with @jameshilliard.  Segwit transactions are optional for inclusion and there is no need for a primary-use client to support their exclusion.  The charter in place for this working group is "segwit + 2x hardfork."  Supporting a resistance to either major component of that is out of scope and likely to harm the compromise itself.

**Comment by opetruzel** [comment]
NACK -- see Jared's remarks.

**Comment by hsjoberg** [comment]
NACK
Miners are already free to mine non-segwit blocks after the activation.

**Comment by jgarzik** [comment]
This is outside the segwit2x charter, which assumes segwit+2M HF activation.
