### ISSUE TITLE
Bump version proportionally to the scope of changes

### ISSUE THREAD

**Issue by meeDamian** [btc1/bitcoin#57]
Even though Bitcoin doesn't follow Semantic Versioning, marking block-based consensus rules change enforcement with a patch-level version change appears confusing and hides the backwards incompatibility aspect of the change.

Minor, or even major, version change would be a lot more appropriate.

Given the fact that all participating nodes are required to upgrade, major version bump would seem more fitting.

**Comment by jli225** [comment]
I have the same feeling. This is a big change, so maybe it shall be 15.0? I am not sure. "15" does not look like a good number. Maybe the hard fork version at 1.0.0.0?
Frankly, such issues are not technical. Instead, they are psychological.
@meeDamian What's your opinion?

**Comment by jgarzik** [comment]
The major version was already bumped.
