### ISSUE TITLE
Segwit address format

### ISSUE THREAD

**Issue by jli225** [btc1/bitcoin#70]
Introducing new address format in the application layer is a very important decision that we should be highly conscientious to make. 

[Two BS employees proposed a new format specifically for SegWit address "bc1".](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki)  Although they did not give any explanation in that proposal, some other Blockstream employees "informed" us elsewhere. [1](https://www.reddit.com/r/Bitcoin/comments/69wk6b/hello_sipa_great_new_segwit_address_format_in/dhaam1h/) [2](https://github.com/sipa/bech32/issues/16)

You can see that such counter-intuitive choice was very controversial even in those censored forums. Unsurprisingly, it was allocated a BIP number (BIP173) quickly by the ~~de~~centralized group and the probability of being merged is extremely high. There are few discussions about this huge change, due to the strategy of current Core. (Similarly, most SW supporters have no idea about the effect of SW on their pitiful nodes.)

None of BS explanations are reasonable, again. For example, If "btc1" is too long, then "b1" would be perfect. Anyway, it's ridiculous to choose "bc1". Moreover, it's irresponsible to allocate "btc1 or bt1 or bc1 or b1" to SegWit address, although Litecoin has chosen ltc1 as the prefix. So, why?

**The reason is, we will introduce new address format in the future inevitably. If we used "b1" for SW address, then what should we use for the new thing? "b2"?** Not acceptable.

A patch should have a patch-style address format. So "s1" or "sw1" is most appropriate. I prefer the latter one.

.

**Comment by keeking** [comment]
Ack. @barmstrong , which one do you prefer?

**Comment by snavsenv** [comment]
You have to ask in the segwit2x dragonsden, this github is only for appearances.

**Comment by tomasvdw** [comment]
SegWit as implemented by btc1 only allows SegWit transactions wrapped in P2SH.

May I suggest we reserve issues to report problems with btc1? Not for general commentary on some future proposal that somebody made somewhere else.

**Comment by jgarzik** [comment]
Yes, let's keep this focused on btc1/segwit2x specific issues for now.
