### ISSUE TITLE
Changning limit of transaction size for HF block

### ISSUE THREAD

**Issue by Zaromet** [btc1/bitcoin#71]
Form my understanding of a code you can't create transaction bigger then 1MB. I would asked to change that for HF block. There is a fee bounty out there for first block over 1MB and it is done in a one transaction bigger then 1MB.

http://www.blockbounties.info/

But I do fear that miners might do anything to orphan that block since fee is that hi... It is about 20 blocks... Thoughts?

This might be a good idea even without this bounty. Miner can make a 1MB+ transaction ready for this block and have it in mempool... It will not be mined until needed.

**Comment by tomasvdw** [comment]
No. The bounty transaction is exactly 1,000,000 bytes. This is allowed when the blocksize increase takes effect.

The reason it can only be included before the increase, is because with the 1mb blocksize limit it doesn't fit because the header takes 80 bytes.

There are good reasons to keep the transaction limit at 1,000,000 bytes.

**Comment by Zaromet** [comment]
OK my mistake then. I though it was over 1MB size... And I was talking about only 1 block. The one that needs to be 1MB+ not every block after that... So you are 100% sure? I can file this under another lie I was told by core dev...

**Comment by tomasvdw** [comment]
I am 100% sure. 

Note, I don't think the bounty will work for this _scheduled_ increase as it can be trivially retracted by the author.

**Comment by gmaxwell** [comment]
Allowing a transaction larger than was ever possible before technically puts this software into an untested space of operations in additional ways. Are the authors of it prepared to test that extensively enough to determine the actual consequences?

**Comment by Zaromet** [comment]
OK since it is 1MB there is no need to do that then.

@gmaxwell 1 block. None is talking forever... Unless you are talking about 80 bytes extra. In that case stop trolling...

**Comment by jgarzik** [comment]
Just to put a final cap on this:  Transactions are capped at 1M in practice, in the field, by long deployed wallet code.  segwit2x has a proto-BIP that codifies existing field practice: https://github.com/btc1/specifications/blob/master/drafts/BIP-tx-size.md   The intent of the BIP is to document existing in-the-field limits, and maintain those limits in the node software as block size increases.
