### ISSUE TITLE
Production release

### ISSUE THREAD

**Issue by HashSquatch** [btc1/bitcoin#73]
Good day,

I know that everyone is under stress currently. Looking over the last few commits, I'm curious to know if btc1 ready for production release? The set release day is meant to be today correct? By when can we compile and run nodes? What more has to be done?

**Comment by onlimono** [comment]
I wanna know either. Anybody can answer?

**Comment by NLNicoo** [comment]
[[Bitcoin-segwit2x] Release candidate this weekend](https://lists.linuxfoundation.org/pipermail/bitcoin-segwit2x/2017-July/000139.html)

**Comment by floreslorca** [comment]
this weekend? its almost over

**Comment by huanzhang12** [comment]
The new release (Version 1.14.4) has just been pushed to the repository. This issue can be closed.
