### ISSUE TITLE
Change the protocol version message bytes (pchMessageStart)

### ISSUE THREAD

**Issue by shesek** [btc1/bitcoin#76]
To prevent incompatible 2x and non-2x nodes from connecting to each-other, as was [already done for the segwit2x testnet](https://github.com/btc1/bitcoin/commit/f831744fdcf18361436e8059a54cbfacac99b4f1#diff-64cbe1ad5465e13bc59ee8bb6f3de2e7L214).

**Comment by christophebiocca** [comment]
That was done to start a brand new, wholly unrelated testnet (testnet5).

Doing this to mainnet would break compatibility with all other full nodes (including compatible BU nodes, or non-2x nodes pre-split, which are compatible) and with all existing SPV clients.

In other words, a very bad idea.

**Comment by shesek** [comment]
Are BU nodes compatible? Segwit2x has several additional consensus rules (large block on forking point, the changes regarding transaction maximum size, etc) that make it incompatible with all other node software, AFAIK.

Agreed that the version bytes should remain the same pre-HF, but I think that they should change to indicate incompatibility as soon as the HF is active. If/when BU and other node software applies the necessary changes to be 2x-compatible, they could move over to the new version bytes as well.

**Comment by jgarzik** [comment]
That was only for testnet.

**Comment by shesek** [comment]
Why not on mainnet as well? 2x nodes are obviously not compatible with existing node software. 2x and legacy nodes have no business connecting to one another post-HF, they'll just ban each-other anyway. But until they do, this will worsen the effects of replay attack and make the network partition in odd, unexpected ways, instead of in a straightforward, predictable way.

**Comment by christophebiocca** [comment]
SPV nodes will all break with such a change, for one.

**Comment by shesek** [comment]
Yes, SPV nodes will have to choose to use the new network in the same way that full nodes do, instead of being coerced into it. Why is that a bad thing?

**Comment by shesek** [comment]
Also, this makes segwit2x's testnet results much less reliable. Segwit2x testnet nodes are isolated and don't have to deal with non-compatible node software feeding them data, in the way that segwit2x mainnet nodes will on the live network.

At the very least, you should revert the testnet version bytes change, so it'll more closely match real world conditions.
