### ISSUE TITLE
Change logo color to match colorscheme of coinbase, bitpay, blockchain.info

### ISSUE THREAD

**Issue by snavsenv** [btc1/bitcoin#82]
Hello, i tried looking in the code was unable to find where to change the color of the splash logo to blue so that it matches the color scheme of Blockchain.info, Coinbase and bitpay who also operate in blue.

This is the mockup i made in paint, let me know what you think.

Have a nice day. 

![image](https://user-images.githubusercontent.com/30059949/28258486-b71bdbd6-6ad1-11e7-815f-5a6c5f4586e9.png)

**Comment by pekatete** [comment]
Orange is the new black, and orange has always been the bitcoin logo color (core brand with logo on black), so no need for blue, however pleasing to eye I find it.

**Comment by jgarzik** [comment]
Out of scope for this project
