### ISSUE TITLE
warning='1 of last 100 blocks have unexpected version'

### ISSUE THREAD

**Issue by ucwong** [btc1/bitcoin#91]
UpdateTip: new best=0000000000000000008810a4808837c4f3372a9ad041fb78ba88877ee6e975a6 height=476506 version=0x20000010 log2_work=86.784813 tx=240316839 date='2017-07-19 09:30:30' progress=1.000000 cache=75.2MiB(20428tx) warning='1 of last 100 blocks have unexpected version'

**Comment by jgarzik** [comment]
Please see already-filed Issue #30
