### ISSUE TITLE
Review per-txout indexing and storage

### ISSUE THREAD

**Issue by jgarzik** [btc1/bitcoin#94]
Review and consider merging the Bitcoin Core per-txout work.

**Comment by snavsenv** [comment]
?

**Comment by omersiar** [comment]
@snavsenv Why do you even have a GitHub account? It is a common practice to use GitHub's issue facility to take notes.

**Comment by jgarzik** [comment]
In progress on `segwit2x-dev` branch

**Comment by omersiar** [comment]
Why is this in progress on a development branch? Segwit2X was not called off already?

**Comment by jgarzik** [comment]
@omersiar It will get moved to another branch, and the segwit2x branches will be retired.
