### ISSUE TITLE
Other quadratic delays that can be mitigated with no consensus rule changes

### ISSUE THREAD

**Issue by SergioDemianLerner** [btc1/bitcoin#97]
The following old post of mine describes other ways to create a block that would take, in btc1 post HF, about 20  seconds to process, in a standard PC.

https://bitslog.wordpress.com/2017/04/17/new-quadratic-delays-in-bitcoin-scripts/

These problems could be fixed just by improving the efficiency of the code.

**Comment by maddenw** [comment]
This should be closed.
